### ISSUE TITLE
fix for -- "Unhandled exception: InvalidOperationException - Transaction 131785960486885089 is currently reading data. Cannot issue another read/write until the read completes ...

### ISSUE THREAD

**Issue by pisees** [toddabel/PQService#5]
Hi Todd,

I had to change to follow code otherwise I was getting an exception. Any thoughts?

case QueueType.AllQueues:
                            //var result = Parallel.For(0, _queueNames.Length, async (i) =>
                            //{
                            //    var q = await GetQueueAsync(i).ConfigureAwait(false);
                            //    Interlocked.Add(ref totalCount, await q.GetCountAsync(tx).ConfigureAwait(false));
                            //});
                            for (int i = 0; i < _queueNames.Length; i++)
                            {
                                var q = await GetQueueAsync(i).ConfigureAwait(false);
                                totalCount += q.GetCountAsync(tx).GetAwaiter().GetResult();
                            }
                            break;

**Comment by toddabel** [comment]
From the fix, it looks like a bug with timing access to the queue. Did you have to change the await for q.GetCountAsync(tx) to make this work or was it just the Parallel.For?

**Comment by pisees** [comment]
Hi Todd,

It was the Parallel.For:

"Message": "Unhandled exception: InvalidOperationException - Transaction 131785960486885089 is currently reading data. Cannot issue another read/write until the read completes at    at Microsoft.ServiceFabric.Replicator.TransactionStateMachine.ThrowExceptionCallerHoldsLock()
       at Microsoft.ServiceFabric.Replicator.TransactionStateMachine.OnBeginRead()
       at Microsoft.ServiceFabric.Replicator.Transaction.<GetVisibilitySequenceNumberAsync>d__13.MoveNext()
    --- End of stack trace from previous location where exception was thrown ---
       at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
       at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
       at System.Fabric.Store.TStore`5.<CreateComponentEnumerableAsync>d__328.MoveNext()
    --- End of stack trace from previous location where exception was thrown ---
       at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
       at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
       at System.Fabric.Store.TStore`5.<CreateEnumerableAsync>d__327.MoveNext()
    --- End of stack trace from previous location where exception was thrown ---
       at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
       at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
       at Microsoft.ServiceFabric.Data.Collections.DistributedQueue`1.<GetCountAsync>d__66.MoveNext()
    --- End of stack trace from previous location where exception was thrown ---
       at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
       at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
       at System.Runtime.CompilerServices.ConfiguredTaskAwaitable`1.ConfiguredTaskAwaiter.GetResult()
       at QuickService.QueueService.QueuePartitionOperations`2.<>c__DisplayClass49_1.<<CountAsync>b__0>d.MoveNext() in C:\Users\kurtsc\Documents\GitHub\PQService\src\QueueService\QueuePartitionOperations.cs:line 822
    --- End of stack trace from previous location where exception was thrown ---
       at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
       at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)m()
       at System.Threading.ThreadPoolWorkQueue.Dispatch()",

       at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
       at System.Threading.QueueUserWorkItemCallback.System.Threading.IThreadPoolWorkItem.ExecuteWorkItem()
       at System.Threading.ThreadPoolWorkQueue.Dispatch()",

**Comment by pisees** [comment]
Working on a fix, but backed out for now: https://github.com/toddabel/PQService/pull/6/commits/85108b243797a9ce9609423325d839cacc0b1f55
